# Forçando uma releitura pelo GitHub Actions v3
name: Atualizacao Diaria de Dados

on:
  schedule:
    - cron: '0 2 * * *'
  
  workflow_dispatch:

jobs:
  update-data-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4
        with:
          # Especifica um caminho para o checkout para ter controle total
          path: './-criptopreditor-web'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas ccxt

      - name: Rodar Script de Coleta
        # Aponta para o diretorio onde o codigo foi baixado
        working-directory: ./-criptopreditor-web
        run: python coleta_dados.py

      - name: Commit dos Arquivos Atualizados
        # Aponta para o mesmo diretorio para encontrar os arquivos
        working-directory: ./-criptopreditor-web
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualização automática dos dados históricos"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          file_pattern: "Historico_Moedas/*.csv"
